// console.log("Hello world")
function getWeatherData(loc) {
    const weatherData = [
      {
        location: "Kolkata",
        lastUpdatedEpoch: 1677819600,
        lastUpdated: "2023-03-03 10:30",
        tempC: 33,
        tempF: 91.4,
        isDay: 1,
        condition: {
          text: "Mist",
          icon: "//cdn.weatherapi.com/weather/64x64/day/143.png",
          code: 1030,
        },
        windMph: 6.9,
        windKph: 11.2,
        windDegree: 350,
        windDir: "N",
        pressureMb: 1018,
        pressureIn: 30.06,
        precipMm: 0,
        precipIn: 0,
        humidity: 34,
        cloud: 0,
        feelslikeC: 30.9,
        feelslikeF: 87.5,
        visKm: 3.5,
        visMiles: 2,
        uv: 8,
        gustMph: 7.4,
        gustKph: 11.9,
      },
      {
        location: "London",
        lastUpdated_epoch: 1677819600,
        lastUpdated: "2023-03-03 05:00",
        tempC: 4,
        tempF: 39.2,
        isDay: 0,
        condition: {
          text: "Overcast",
          icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
          code: 1009,
        },
        windMph: 4.3,
        windKph: 6.8,
        windDegree: 40,
        windDir: "NE",
        pressureMb: 1028,
        pressureIn: 30.36,
        precipMm: 0,
        precipIn: 0,
        humidity: 75,
        cloud: 100,
        feelslikeC: 1.3,
        feelslikeF: 34.3,
        visKm: 10,
        visMiles: 6,
        uv: 1,
        gustMph: 11,
        gustKph: 17.6,
      },
      {
        location: "SanFransisco",
        lastUpdated_epoch: 1677819600,
        lastUpdated: "2023-03-03 01:00",
        tempC: 25,
        tempF: 77,
        isDay: 0,
        condition: {
          text: "Clear",
          icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
          code: 1000,
        },
        windMph: 6.9,
        windKph: 11.2,
        windDegree: 10,
        windDir: "N",
        pressureMb: 1009,
        pressureIn: 29.8,
        precipMm: 0,
        precipIn: 0,
        humidity: 79,
        cloud: 0,
        feelslikeC: 26.9,
        feelslikeF: 80.4,
        visKm: 10,
        visMiles: 6,
        uv: 1,
        gustMph: 13,
        gustKph: 20.9,
      },
      {
        location: "Mumbai",
        lastUpdated_epoch: 1677819600,
        lastUpdated: "2023-03-03 10:30",
        tempC: 31,
        tempF: 87.8,
        isDay: 1,
        condition: {
          text: "Overcast",
          icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
          code: 1009,
        },
        windMph: 4.3,
        windKph: 6.8,
        windDegree: 190,
        windDir: "S",
        pressureMb: 1018,
        pressureIn: 30.06,
        precipMm: 0,
        precipIn: 0,
        humidity: 41,
        cloud: 0,
        feelslikeC: 32.2,
        feelslikeF: 89.9,
        visKm: 1.8,
        visMiles: 1,
        uv: 7,
        gustMph: 8.7,
        gustKph: 14,
      },
      {
        loaction: "Chennai",
        lastUpdated_epoch: 1677819600,
        lastUpdated: "2023-03-03 10:30",
        tempC: 29,
        tempF: 84.2,
        isDay: 1,
        condition: {
          text: "Mist",
          icon: "//cdn.weatherapi.com/weather/64x64/day/143.png",
          code: 1030,
        },
        windMph: 8.1,
        windKph: 13,
        windDegree: 60,
        windDir: "ENE",
        pressureMb: 1019,
        pressureIn: 30.09,
        precipMm: 0,
        precipIn: 0,
        humidity: 70,
        cloud: 50,
        feelslikeC: 30.5,
        feelslikeF: 86.9,
        visKm: 3,
        visMiles: 1,
        uv: 7,
        gustMph: 9.6,
        gustKph: 15.5,
      },
      {
        loaction: "Orissa",
        lastUpdated_epoch: 1677819600,
        lastUpdated: "2023-03-03 07:00",
        tempC: 1,
        tempF: 33.8,
        isDay: 0,
        condition: {
          text: "Overcast",
          icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
          code: 1009,
        },
        windMph: 9.4,
        windKph: 15.1,
        windDegree: 290,
        windDir: "WNW",
        pressureMb: 1006,
        pressureIn: 29.71,
        precipMm: 0,
        precipIn: 0,
        humidity: 93,
        cloud: 100,
        feelslikeC: -5.4,
        feelslikeF: 22.3,
        visKm: 10,
        visMiles: 6,
        uv: 1,
        gustMph: 32.9,
        gustKph: 52.9,
      },
      {
        location: "Agra",
        lastUpdated_epoch: 1677819600,
        lastUpdated: "2023-03-03 10:30",
        tempC: 30.2,
        tempF: 86.4,
        isDay: 1,
        condition: {
          text: "Sunny",
          icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
          code: 1000,
        },
        windMph: 8.1,
        windKph: 13,
        windDegree: 303,
        windDir: "WNW",
        pressureMb: 1020,
        pressureIn: 30.11,
        precipMm: 0,
        precipIn: 0,
        humidity: 20,
        cloud: 3,
        feelslikeC: 28,
        feelslikeF: 82.4,
        visKm: 10,
        visMiles: 6,
        uv: 8,
        gustMph: 9.2,
        gustKph: 14.8,
      },
      {
        location: "Bangalore",
        lastUpdated_epoch: 1677820500,
        lastUpdated: "2023-03-03 10:45",
        tempC: 26,
        tempF: 78.8,
        isDay: 1,
        condition: {
          text: "Sunny",
          icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
          code: 1000,
        },
        windMph: 13.6,
        windKph: 22,
        windDegree: 90,
        windDir: "E",
        pressureMb: 1024,
        pressureIn: 30.24,
        precipMm: 0,
        precipIn: 0,
        humidity: 23,
        cloud: 0,
        feelslikeC: 24.6,
        feelslikeF: 76.2,
        visKm: 10,
        visMiles: 6,
        uv: 7,
        gustMph: 16.6,
        gustKph: 26.6,
      },
      {
        location: "Gujarat",
        lastUpdated_epoch: 1677820500,
        lastUpdated: "2023-03-03 10:45",
        tempC: 30,
        tempF: 86,
        isDay: 1,
        condition: {
          text: "Overcast",
          icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
          code: 1009,
        },
        windMph: 4.3,
        windKph: 6.8,
        windDegree: 90,
        windDir: "E",
        pressureMb: 1019,
        pressureIn: 30.09,
        precipMm: 0,
        precipIn: 0,
        humidity: 29,
        cloud: 0,
        feelslikeC: 27.8,
        feelslikeF: 82,
        visKm: 3,
        visMiles: 1,
        uv: 8,
        gustMph: 8.3,
        gustKph: 13.3,
      },
      {
        location: "Hyderabad",
        lastUpdated_epoch: 1677820500,
        lastUpdated: "2023-03-03 10:45",
        tempC: 31,
        tempF: 87.8,
        isDay: 1,
        condition: {
          text: "Sunny",
          icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
          code: 1000,
        },
        windMph: 4.3,
        windKph: 6.8,
        windDegree: 180,
        windDir: "S",
        pressureMb: 1023,
        pressureIn: 30.21,
        precipMm: 0,
        precipIn: 0,
        humidity: 24,
        cloud: 0,
        feelslikeC: 29.1,
        feelslikeF: 84.4,
        visKm: 6,
        visMiles: 3,
        uv: 8,
        gustMph: 8.7,
        gustKph: 14,
      },
    ];
    var found = weatherData.filter( (ele) => {
      return ele.location === loc;
    });
    return found;
  }
  
  var data = getWeatherData("Kolkata");
  console.log(data);
  